name: 'ski_resorts_pipeline'
version: '1.0.0'

profile: 'ski_resorts_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  ski_resorts_pipeline:
    bronze:
      +materialized: table
      +schema: bronze
      +warehouse: ski_wh
    silver:
      +materialized: table
      +schema: silver
      +warehouse: ski_wh
    gold:
      +materialized: view
      +schema: gold
      +warehouse: ski_wh